name: Build Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ vars.JDK_VERSION }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            gradle-wrapper.jar
          key: ${{ github.ref_name }}-gradle-cache
          restore-keys: |
            ${{ github.ref_name }}-gradle-cache

      - name: Set executable permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build Plugin
        run: ./gradlew buildPlugin --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-distributions
          path: build/distributions/*.zip
          retention-days: 7
